AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a smaple EC2
# Mappings:
#   RegionMap:
#     us-east-1:
#       AMI: ami-0cff7528ff583bf9a
#     us-west-2:
#       AMI: ami-02d1e544b84bf7502
    

Resources:
  TestEC2:
    Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0cff7528ff583bf9a
      # Fn::FindInMap: 
      #   - "RegionMap"
      #   - Ref: "AWS::Region"
      #   - "AMI"
    InstanceType: t2.micro